### ISSUE TITLE
Failure to parse JSON should emit 400 not 500

### ISSUE THREAD

**Issue by rauchg** [zeit/micro-core#4]

**Comment by TooTallNate** [comment]
Is this for client upload, or server response?

**Comment by onbjerg** [comment]
I can't figure out what this issue is about, either. When I use ``json(req)`` from this package, and the body is malformed (i.e. not JSON), then the server emits 400.

**Comment by onbjerg** [comment]
@TooTallNate This issue has been fixed AFAIK.

**Comment by TooTallNate** [comment]
[This](https://github.com/zeit/micro-core/blob/90a78fa1e182e7c02520e508e55ecb728c58edab/lib/index.js#L43) does indeed seem correct according to the issue title. Close?

**Comment by onbjerg** [comment]
@TooTallNate Confirmed this behavior on my production apps as well.
